version: "2.1"
services:
  # db:
  #   image: mysql:5
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   healthcheck:
  #     test: "exit 0"
  #   ports:
  #     - 3306:3306
  #   environment:
  #     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  #     - MYSQL_ROOT_PASSWORD = joe123
  #     - MYSQL_DATABASE = fasahny
  #     - MYSQL_USER = root
  #     - MYSQL_PASSWORD = joe123
  app:
    build: .
    ports:
      - 4000:3000
    # depends_on:
    #    db:
    #       condition: service_healthy



